from es.es import es_client
from es_connection import es_connect
from es.es_config import AmenitiesConfiguration
from helpers import hashFileName, removePuntautions


amenities = [
"airport",
"amusement park",
"aquarium",
"art gallery",
"atm",
"bakery",
"bank",
"bar",
"barbers",
"beach",
"beauty salon",
"bicycle store",
"book store",
"bookies",
"bowling alley",
"buddhist temple",
"bus station",
"cafe",
"campground",
"car dealer",
"car rental",
"car repair",
"car wash",
"caravan park",
"casino",
"cemetery",
"church",
"cinemas",
"city hall",
"clothing store",
"coffee",
"coffee shop",
"comedy club",
"convenience store",
"courthouse",
"cricket club",
"cricket ground",
"day care centre",
"dentist",
"department store",
"doctor",
"drugstore",
"electrician",
"electronics store",
"embassy",
"estate agent",
"fire station",
"florist",
"food",
"football clubs",
"football field",
"football stadium",
"funeral home",
"furniture store",
"gas station",
"golf courses",
"gp",
"groceries",
"gym",
"hair care",
"hair dressers",
"hardware store",
"health club",
"hiking area",
"hindu temple",
"home goods store",
"hospital",
"hotels",
"insurance agency",
"jewelry store",
"laundry",
"lawyer",
"leisure centre",
"lgbtq",
"library",
"light rail station",
"liquor store",
"local convenience store",
"local government office",
"locksmith",
"lodging",
"m1 motorway",
"m25 motorway",
"m4 motorway",
"markets",
"meal delivery",
"meal takeaway",
"mosque",
"movie rental",
"movie theater",
"moving company",
"museum",
"national park",
"night club",
"nursery",
"opticians",
"outdoor activities",
"painter",
"park",
"park and ride",
"parking",
"pet store",
"petrol station",
"pharmacy",
"physiotherapist",
"plumber",
"police",
"pool",
"post office",
"primary school",
"pub",
"restaurant",
"rock climbing",
"roofing contractor",
"rooftop bars",
"rooftop garden",
"rugby club",
"rugby stadium",
"school",
"secondary school",
"shoe store",
"shopping centre",
"shopping mall",
"sikh temple",
"skiiing",
"snooker",
"spa",
"speakeasy bar",
"sports hall",
"stadium",
"storage",
"supermarket",
"supermarket",
"swimming pool",
"synagogue",
"taxi stand",
"tech city",
"temple",
"tennis ",
"tennis court",
"theatre",
"theme park",
"tourist attraction",
"train station",
"travel agency",
"university",
"veterinary care",
"zoo",
  "Abertay University",
  "Aberystwyth University",
  "Anglia Ruskin University",
  "Arden University",
  "Aston University Birmingham",
  "Bangor University",
  "University of Bath",
  "Bath Spa University",
  "University of Bedfordshire",
  "University of Birmingham",
  "Birmingham City University",
  "University College Birmingham",
  "Bishop Grosseteste University",
  "University of Bolton",
  "The Arts University Bournemouth",
  "Bournemouth University",
  "BPP University",
  "University of Bradford",
  "University of Brighton",
  "University of Bristol",
  "Brunel University",
  "University of Buckingham",
  "Buckinghamshire New University",
  "The iconic King's College Chapel of the University of Cambridge",
  "University of Cambridge",
  "Canterbury Christ Church University",
  "Cardiff Metropolitan University",
  "Cardiff University",
  "University of Chester",
  "University of Chichester",
  "Coventry University",
  "Cranfield University",
  "University for the Creative Arts",
  "University of Cumbria",
  "De Montfort University",
  "University of Derby",
  "University of Dundee",
  "Durham Castle",
  "Durham University",
  "Earlham Hall at the University of East Anglia",
  "University of East Anglia",
  "University of East London",
  "Edge Hill University",
  "The Old College of the University of Edinburgh",
  "University of Edinburgh",
  "Edinburgh Napier University",
  "University of Essex",
  "University of Exeter",
  "Falmouth University",
  "University of Glasgow",
  "Glasgow Caledonian University",
  "University of Gloucestershire",
  "University of Greenwich",
  "Harper Adams University",
  "Hartpury University",
  "Heriot-Watt University",
  "University of Hertfordshire",
  "University of the Highlands & Islands",
  "University of Huddersfield",
  "University of Hull",
  "Imperial College London",
  "Keele University",
  "University of Kent",
  "Kingston University",
  "University of Central Lancashire",
  "Lancaster University",
  "The Parkinson Building at the University of Leeds",
  "University of Leeds",
  "Leeds Arts University",
  "Leeds Beckett University",
  "Leeds Trinity University",
  "University of Leicester",
  "University of Lincoln",
  "University of Liverpool",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "University of London",
  "London Metropolitan University",
  "London South Bank University",
  "Loughborough University",
  "University of Manchester",
  "Manchester Metropolitan University",
  "Middlesex University London",
  "Newcastle University",
  "Newman University",
  "University of Northampton",
  "Northumbria University",
  "Norwich University of the Arts",
  "University of Nottingham",
  "Nottingham Trent University",
  "The Open University",
  "University of Oxford",
  "Oxford Brookes University",
  "Plymouth Marjon University",
  "University of Plymouth",
  "University of Portsmouth",
  "Queen Margaret University",
  "Queen's University Belfast",
  "Ravensbourne University London",
  "Foxhill House",
  "University of Reading",
  "Regent's University London",
  "The Robert Gordon University",
  "Roehampton University",
  "Royal Agricultural University",
  "University of Salford",
  "University of Sheffield",
  "Sheffield Hallam University",
  "University of South Wales",
  "University of Southampton",
  "Solent University",
  "St Salvator's Quad at the University of St Andrews",
  "University of St Andrews",
  "St Mary's University",
  "Staffordshire University",
  "University of Stirling",
  "University of Strathclyde",
  "University of Suffolk",
  "University of Sunderland",
  "University of Surrey",
  "University of Sussex",
  "Swansea University",
  "Teesside University",
  "University of Ulster",
  "University of the Arts London",
  "Ulster University Coleraine",
  "University of Law",
  "University of Wales",
  "University of Warwick",
  "University of the West of England",
  "University of the West of Scotland",
  "University of West London",
  "University of Westminster",
  "University of Winchester",
  "University of Wolverhampton",
  "University of Worcester",
  "Wrexham Glyndŵr University",
  "University of York",
  "York St John University",
  "B & M",
  "B & Q",
  "Wickes",
  "Homebase",
  "Tony & Guy",
  "Supercut",
  "Amba Hotels",
  "Audley Trave",
  "Best Western",
  "Bloc Hotels",
  "Butlins",
  "Champneys",
  "Comfort Inn",
  "Corus Hotel",
  "Crerar Hotel",
  "Crowne Plaza",
  "Dorchester Collection Hotels",
  "easyHotel",
  "Edwardian Hotel",
  "Exclusive Hotels",
  "Forest Holidays",
  "Four Seasons Hotels",
  "Grange Hotel",
  "Haven Holidays",
  "Hayes & Jarvis",
  "Hilton",
  "Holiday Inn",
  "Hotel du Vin",
  "Hyatt",
  "Ibis",
  "Inkeepers Lodge",
  "InterContinental Hotels",
  "Jurys Inn",
  "Kempinski Hotel",
  "MacDonald Hotels",
  "Malmaison",
  "Marriott",
  "McMillan Hotel",
  "Mercure Hotels",
  "Metro Inn",
  "Mr & Mrs Smith",
  "Novotel",
  "Old English Inn",
  "Onefinestay",
  "Park Inn",
  "Park Plaza Hotels & Resorts",
  "Peel Hotel",
  "Premier Inn",
  "Principal Hotel Company",
  "QHotel",
  "Radisson",
  "Ramada",
  "Ritz",
  "Ritz-Carlton",
  "Savoy Hotel",
  "Shangri-La Hotels",
  "Sheraton Hotels and Resorts",
  "Silverse",
  "Thistle Hotels",
  "Titan Travel",
  "Travelodge",
  "umi Hotel",
  "Village Hotel Club",
  "Yotel" ,
  "ASDA",
  "Best One",
  "Booths",
  "Budgens",
  "Costco",
  "Costcutter",
  "Farmfoods",
  "Happy Shopper",
  "Heron Foods",
  "Iceland",
  "Julian Graves",
  "Lidl",
  "Londis",
  "M & S Food",
  "Makro",
  "Morrisons",
  "Netto",
  "Nisa",
  "Ocado",
  "Planet Organic",
  "Premier Stores",
  "Sains",
  "SPAR",
  "Sprout Farmers Market",
  "Tesco",
  "Tesco Express",
  "The Co-operative Food",
  "Waitrose",
  "Whole Foods Market" ,
  "Asda Petrol",
  "ATS Euromaster",
  "Avon Tyres",
  "BP",
  "Bridgestone",
  "Continental",
  "Dunlop",
  "Elf",
  "Esso",
  "Goodyear",
  "Gulf",
  "Hankook",
  "Jet",
  "Michelin",
  "Morrison's Petrol",
  "Murc",
  "Nexen Tir",
  "Pirelli",
  "Q",
  "Sains",
  "Shell",
  "Tesco Petrol",
  "Texaco",
  "Total",
  "Yokohama Tyres",
  "Black & Lizars",
  "Boots opticians",
  "Costco Optical",
  "David Clulow",
  "Duncan & Todd",
  "Hakim Group",
  "Leightons",
  "Optical Express",
  "Scrivens Opticians & Hearing Care",
  "Specsavers",
  "Vision Express",
  "Antic Collective",
  "Bay Restaurant Group",
  "Belushi's",
  "Brewers Fayre",
  "Chef & Brewer",
  "Chicago Rock Cafe",
  "Eerie Pub Company",
  "Faucet Inn",
  "Firkin Brewery",
  "Food & Fuel Pubs",
  "Greene King",
  "Harvey's Brewery",
  "Mana Bar",
  "O'Neill's (pub chain)",
  "Porterhouse Brewery",
  "Punch Pubs",
  "Revolution Bars Group",
  "Scream Pubs",
  "Slug and Lettuce",
  "Spirit Group",
  "Spirit Pub Company",
  "Steamin' Billy",
  "Stonegate Pub Company",
  "Tynemill",
  "Varsity (pub chain)",
  "Walkabout (pub chain)",
  "Wells & Co",
  "Wetherspoons",
  "Yates's",
  "Young's",
  "IKEA",
  "Wilko",
  "B&Q",
  "John Lewis",
  "Screwfix",
  "Wickes",
  "Dunelm",
  "Home",
  "De",
  "House of Fraser",
  "Dreams",
  "ao.com",
  "Habitat",
  "Topps Tiles",
  "Bensons",
  "Carpetright",
  "Furniture Village",
  "HomeSense",
  "Wren Kitchens",
  "Sofology",
  "Howdens",
  "Sharp's",
  "ScS",
  "Loa",
  "Multiyor" ,
  "Curzon Cinemas",
  "Curzon Home Cinema",
  "Empire Cinemas",
  "Everyman Cinemas",
  "Gaumont-British",
  "Merlin Cinemas",
  "Movie House Cinemas",
  "Odeon Cinemas",
  "Picturehouse Cinemas",
  "Reel Cinemas UK",
  "Regal Cinemas (UK)",
  "Scott Cinemas",
  "Showcase Cinemas",
  "The Cannon Group Inc.",
  "The Light Cinemas",
  "Vue Cinemas" ,
  "Genting the colony club casino",
  "Crockford casino",
  "Maxims casino club",
  "Crown aspinals",
  "Napoleon casino",
  "Genting casino",
  "The clermont club",
  "The palm beach casino",
  "Grosvenor casino" ,
  "Ladbrokes",
  "Coral",
  "Betfred",
  "Paddy Power" ,
  "Enterprise",
  "Hertz",
  "Sixt",
  "Firefly",
  "Budget",
  "Avis",
  "Eurocar",
  "Dollar car rental",
  "Green Motion" ,
  "Alliance & Leicester",
  "Bank of Scotland",
  "Barclays Bank",
  "Bradford & Bingley",
  "Bristol & West",
  "Britannia Building Society",
  "Cheltenham & Gloucester",
  "Close Brothers",
  "Clydesdale Bank",
  "Co-operative Bank",
  "Halifax",
  "HSBC",
  "Lloyds TSB",
  "Nationwide Building Society",
  "Natwest",
  "Northern Bank",
  "Portman",
  "Royal Bank of Scotland",
  "Santander",
  "Schroders",
  "Standard Chartered Bank",
  "Standard Life Bank",
  "Tesco bank",
  "Woolwich Building Society",
  "Yorkshire Building Society" ,
  "Bruntingthorpe Aerodrome",
  "East Midlands Airport",
  "RAF Coningsby",
  "RAF Cranwell",
  "Derby Airfield",
  "RAF Barkston Heath",
  "Deenethorpe Aerodrome",
  "Leicester Airport",
  "Sturgate Airfield",
  "Wickenby Aerodrome",
  "RAF Syerston",
  "Gamston Airport",
  "RAF Scampton",
  "Silverstone Heliport",
  "Fenland Airfield",
  "RAF Wittering",
  "Strubby Airfield[2]",
  "Sywell Aerodrome",
  "Nottingham Airport",
  "RAF Waddington",
  "Netherthorpe Airfield",
  "Elstree Airfield",
  "Audley End Airfield",
  "Beccles Airport",
  "Bedford Aerodrome",
  "Castle Mill Airfield[3]",
  "Bourn Airfield",
  "Andrewsfield Aerodrome",
  "Rougham Airfield[4]",
  "Fowlmere Airfield",
  "Cambridge International Airport",
  "Clacton Airport",
  "Cranfield Airport",
  "Northrepps Aerodrome",
  "Duxford Aerodrome",
  "Great Yarmouth - North Denes Airport",
  "Earls Colne Airfield",
  "RAF Henlow",
  "Hethel Airport[5]",
  "RAF Honington",
  "Crowfield Airfield",
  "Elmsett Airfield[6]",
  "RAF Lakenheath",
  "Luton Airport",
  "RAF Marham",
  "RAF Mildenhall",
  "North Weald Airfield",
  "Norwich Airport",
  "Seething Airfield",
  "Old Buckenham Airport",
  "RAF Coltishall",
  "Shuttleworth (Old Warden) Aerodrome",
  "Peterborough Business Airport",
  "Peterborough/Sibson Airport",
  "Shipdham Airfield",
  "RAF Wyton",
  "Little Gransden Airfield",
  "London Southend Airport",
  "Stansted Airport",
  "Stapleford Aerodrome",
  "Wattisham Airfield",
  "Panshanger Airport",
  "London Biggin Hill Airport",
  "Damyns Hall Aerodrome",
  "Heathrow Airport",
  "RAF Northolt",
  "London City Airport",
  "London Heliport",
  "RAF Boulmer",
  "Eshott Airfield",
  "Teesside International Airport",
  "Newcastle International Airport",
  "Barrow/Walney Island Airport",
  "Blackpool Airport",
  "Carlisle Lake District Airport",
  "City Airport Manchester",
  "RAF Woodvale",
  "Liverpool John Lennon Airport",
  "Warton Aerodrome",
  "Manchester Airport",
  "RAF Abingdon",
  "Thruxton Aerodrome",
  "Army Air Corps Middle Wallop",
  "Ascot Racecourse Heliport",
  "Bembridge Airport",
  "RAF Benson",
  "Bicester Airfield",
  "RAF Brize Norton",
  "Challock Airfield[7]",
  "Fairoaks Airport",
  "Gatwick Airport",
  "Clipgate Airfield",
  "Dunsfold Aerodrome",
  "Enstone Airfield",
  "Farnborough Airport",
  "Denham Aerodrome",
  "Goodwood Racecourse Heliport",
  "Hammerwood Helipad[8][9]",
  "RAF Halton",
  "Wycombe Air Park/Booker Airport",
  "London Oxford Airport",
  "Shoreham Airport",
  "Lasham Airfield",
  "Lydd Airport",
  "Lashenden (Headcorn) Airfield",
  "Kent International Airport",
  "Redhill Aerodrome",
  "RAF Odiham",
  "Chalgrove Airfield",
  "Popham Airfield",
  "Rochester Airport",
  "Isle of Wight/Sandown Airport",
  "Southampton Airport",
  "Chichester/Goodwood Airport",
  "RAF Weston-on-the-Green",
  "White Waltham Airfield",
  "Blackbushe Airport",
  "MoD Boscombe Down",
  "Bodmin Aerodrome",
  "Royal Marines Base Chivenor",
  "Salisbury Plain Aerodrome",
  "Cheltenham Racecourse Heliport",
  "Gloucestershire Airport",
  "Exeter Airport",
  "Colerne Airfield",
  "RAF Davidstow Moor",
  "RAF Fairford",
  "Eaglescott Airfield",
  "RNAS Culdrose",
  "Henstridge Airfield[10]",
  "Dunkeswell Aerodrome",
  "Hullavington Airport[11]",
  "Bournemouth Airport",
  "Cotswold Airport",
  "RAF Lyneham",
  "Newquay Airport / RAF St Mawgan",
  "RNAS Predannack",
  "Netheravon Airfield[12]",
  "Oaksey Park Airfield[13]",
  "Perranporth Airfield",
  "Portland Heliport[14]",
  "Old Sarum Airfield",
  "Compton Abbas Airfield",
  "Land's End Airport",
  "St Mary's Airport",
  "Truro Aerodrome",
  "former RAF Upavon",
  "Bristol Airport",
  "Middlezoy AerodromeRAF Weston Zoyland",
  "RAF Weston Zoyland",
  "RAF Wroughton",
  "RNAS Merryfield",
  "RNAS Yeovilton",
  "Yeovil Aerodrome",
  "RAF Cosford",
  "Coventry Airport",
  "Birmingham Airport",
  "Shobdon Aerodrome",
  "Sleap Airfield",
  "Tatenhill Airfield",
  "RAF Ternhill",
  "Wellesbourne Mountford Aerodrome",
  "Wolverhampton Airport",
  "Bagby Airfield",
  "Beverley/Linley Hill Airfield",
  "Brough Aerodrome",
  "Breighton Aerodrome",
  "Leeds East Airport",
  "RAF Dishforth",
  "Doncaster Sheffield Airport",
  "Crosland Moor Airfield",
  "Humberside Airport",
  "RAF Leconfield",
  "Leeds Bradford International Airport",
  "Leeds Heliport",
  "RAF Leeming",
  "RAF Linton-on-Ouse",
  "Sandtoft Airfield",
  "Sherburn-in-Elmet Airfield",
  "RAF Topcliffe",
  "Full Sutton Airfield",
  "Elvington Airfield",
  "George Best Belfast City Airport",
  "City of Derry Airport",
  "Enniskillen/St Angelo Airport",
  "Newtownards Airport",
  "Oban Airport",
  "Unst Airport",
  "Benbecula Airport",
  "Barra Airport",
  "Campbeltown Airport (RAF Machrihanish)",
  "Coll Airport",
  "Colonsay Airport",
  "North Ronaldsay Airport",
  "Cumbernauld Airport",
  "Inverness Airport",
  "Scatsta Airport",
  "Dundee Airport",
  "Sumburgh Airport",
  "Eday Airport",
  "Edinburgh Airport",
  "Fair Isle Airport",
  "Foula Airport",
  "Islay Airport",
  "Fife Airport",
  "Kinloss Barracks",
  "Sanday Airport",
  "Leuchars Station",
  "RAF Lossiemouth",
  "Out Skerries Airport",
  "Papa Stour Airport",
  "Papa Westray Airport",
  "Glasgow International Airport",
  "Glasgow Prestwick Airport",
  "Kirkwall Airport",
  "Perth Airport",
  "Stornoway Airport",
  "Broadford Airfield",
  "Stronsay Airport",
  "Tingwall Airport",
  "Tiree Airport",
  "Westray Airport",
  "Whalsay Airport",
  "Wick Airport",
  "RAF Mona",
  "Caernarfon Airport",
  "Cardiff Heliport",
  "Haverfordwest Aerodrome",
  "Chester Hawarden Airport",
  "Llanbedr Airport",
  "Anglesey Airport",
  "RAF Valley",
  "Pembrey Airport",
  "Swansea Airport",
  "Cardiff Airport",
  "Saint Athan",
  "Welshpool Airport",
  "RAF Andreas",
  "Guernsey Airport",
  "Isle of Man Airport",
  "Jersey Airport" ,
  "McDonald's",
  "J D Wetherspoon",
  "Domino's Pizza",
  "Pizza Hut",
  "Costa Coffee",
  "KFC",
  "Pizza Express",
  "Subway",
  "Burger King",
  "Toby Cavery",
  "Nando's",
  "Krispy Kreme",
  "Harvester",
  "Hard Rock Cafe",
  "Harry Ramsden's",
  "Frankie and Benny's",
  "Starbucks",
  "Bella Italia",
  "Millie's Cookies",
  "TGI Friday's",
  "Caffè Nero",
  "Papa John's",
  "Brewers Fayre",
  "Wimpy",
  "Wagamama",
  "Pret a Manger",
  "Zizzi",
  "Prezzo",
  "West Cornwall Pasty Co.",
  "Slug and Lettuce",
  "Beefeater",
  "Patisserie Valerie",
  "Hungry Horse",
  "Planet Hollywood",
  "Debenhams Cafe and Restaurant",
  "Gourmet Burger Kitchen",
  "Little Chef",
  "Ask Italian",
  "Aberdeen Angus Steakhouse",
  "McDelivery",
  "Five Guys",
  "Chiquito",
  "Miller & Carter",
  "All Bar One",
  "EAT.",
  "Taco Bell",
  "Yo! Sushi",
  "Jamie's Italian",
  "Upper Crust",
  "Flaming Grill",
  "Spudulike",
  "Sizzliing Pubs",
  "Fuji",
  "Loch Fyne Restaurant",
  "Wasabli",
  "Las Iguanas",
  "Bill's",
  "Tortilla",
  "Vintage Inns",
  "Wild Beans",
  "Itsu",
  "Giraffe Restaurant",
  "Stonehouse Pizza & Carvery",
  "Coffee Republic",
  "Crown Carveries",
  "Walkabout",
  "Ben's Cookies",
  "Strada",
  "Chipotle Mexican Grill",
  "Côte",
  "BHS Coffee Lounge",
  "Shakeaway",
  "Shake Shack",
  "Leon",
  "Honest Burgers",
  "Paul",
  "Wahaca",
  "Gaucho",
  "Chicken Cottage",
  "Franco Manca",
  "Jimmy Chung's",
  "Flat Iron",
  "Amazon Restaurants",
  "Meat & Shak",
  "Meat Liquor",
  "Pod Restaurant" ,
  "Bannatyne's",
  "Ben Dunne Gyms",
  "Cannons Health Club",
  "David Lloyd Leisure",
  "DW Sports Fitness",
  "Energie Group Gyms",
  "Esporta",
  "Fitness First",
  "Gold's Gym",
  "Gym World",
  "Holmes Place Health Clubs",
  "JD Sports Gym",
  "LA Fitness",
  "LivingWell",
  "Next Generation Club",
  "Nuffield Health",
  "Places for People",
  "Pure Gym",
  "Snap Fitness",
  "Sports Direct Fitness Gyms",
  "The Gym Group",
  "Total Fitness",
  "Village Hotel Club",
  "Virgin Active",
]

class AreaAmenities:
    def __init__(self, amenity):
        self.amenity = amenity

    def __str__(self):
        return self.amenity

    def to_dict(self):
        return {
            "amenity": self.amenity,
            "scope": "local"
        }

# conect to elastic search instance
_es_client = es_client(es_instance=es_connect(), es_index="area_amenities")
# delete previous index
_es_client.delete_index()
# create the elastic search index
_es_client.create_index(configuration_instance=AmenitiesConfiguration)
# add documents to the index
for amenity in amenities:
    _amenity = AreaAmenities(amenity).to_dict()
    _amenity["id"] = hashFileName(removePuntautions(_amenity.get("name")))
    _es_client.add_document(_amenity)
